project_id = "ukkatmoathxhbaelstzo"

[functions.rewrite-content]
verify_jwt = false

[functions.generate-question-explanation]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.generate-blog-from-pdf]
verify_jwt = false

[functions.rewrite-and-post-news]
verify_jwt = false